-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 141,
  ["line_length"] = 6,
  ["lines_per_file"] = 11,
  ["scale"] = 0.5,
  ["shift"] = {50.5 / 64, 1.5 / 64},
  ["sprite_count"] = 64,
  ["width"] = 271,
}
