require("prototypes/util")

require("prototypes/animated-trains")
require("prototypes/locomotive")
require("prototypes/cart")
require("prototypes/rail")
require("prototypes/trainstop")
require("prototypes/rail-signal")
require("prototypes/wheat-grass")
require("prototypes/aurochs")
require("prototypes/attack-proxy")
require("prototypes/technology")
require("prototypes/blood")
require("prototypes/fuel-category")
require("prototypes/reproduction")
require("prototypes/hay")
require("prototypes/feeding")