-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 165,
  ["line_length"] = 8,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {48 / 64, 38.5 / 64},
  ["sprite_count"] = 512,
  ["width"] = 262,
}
