-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 174,
  ["line_length"] = 12,
  ["lines_per_file"] = 19,
  ["scale"] = 0.5,
  ["shift"] = {34.5 / 64, 38 / 64},
  ["sprite_count"] = 224,
  ["width"] = 297,
}
