-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 137,
  ["line_length"] = 11,
  ["lines_per_file"] = 12,
  ["scale"] = 1,
  ["shift"] = {1 / 32, -20.5 / 32},
  ["sprite_count"] = 128,
  ["width"] = 150,
}
