-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 353,
  ["line_length"] = 2,
  ["lines_per_file"] = 2,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -164.5 / 64},
  ["sprite_count"] = 4,
  ["width"] = 364,
}
