-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 9,
  ["height"] = 204,
  ["line_length"] = 15,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {45 / 64, 27 / 64},
  ["sprite_count"] = 2048,
  ["width"] = 294,
}
