-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 5,
  ["height"] = 123,
  ["line_length"] = 15,
  ["lines_per_file"] = 16,
  ["scale"] = 1,
  ["shift"] = {0 / 32, -11.5 / 32},
  -- ["shift"] = {0 / 32, 0 / 32},
  ["sprite_count"] = 1024,
  ["width"] = 144,
}
