-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 82,
  ["line_length"] = 3,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {42 / 64, -2 / 64},
  ["sprite_count"] = 48,
  ["width"] = 166,
}
