-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 1,
  ["height"] = 82,
  ["line_length"] = 4,
  ["lines_per_file"] = 16,
  ["scale"] = 0.5,
  ["shift"] = {44 / 64, -2 / 64},
  ["sprite_count"] = 64,
  ["width"] = 170,
}
